apiVersion: v2
appVersion: 0.11.4
dependencies:
- condition: control-plane.enabled
  name: control-plane
  repository: ""
  version: 0.1.0
- condition: continuous-delivery.enabled
  name: continuous-delivery
  repository: ""
  version: 0.1.0
description: A Helm chart for Kubernetes
name: keptn
type: application
version: 0.11.4
